// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package keyvalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeyValueServiceClient is the client API for KeyValueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyValueServiceClient interface {
	HasValue(ctx context.Context, in *HasValueRequest, opts ...grpc.CallOption) (*HasValueResponse, error)
	GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*Value, error)
	SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error)
	Transact(ctx context.Context, opts ...grpc.CallOption) (KeyValueService_TransactClient, error)
}

type keyValueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyValueServiceClient(cc grpc.ClientConnInterface) KeyValueServiceClient {
	return &keyValueServiceClient{cc}
}

func (c *keyValueServiceClient) HasValue(ctx context.Context, in *HasValueRequest, opts ...grpc.CallOption) (*HasValueResponse, error) {
	out := new(HasValueResponse)
	err := c.cc.Invoke(ctx, "/apidefinitions.keyval.KeyValueService/HasValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) GetValue(ctx context.Context, in *GetValueRequest, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/apidefinitions.keyval.KeyValueService/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) SetValue(ctx context.Context, in *SetValueRequest, opts ...grpc.CallOption) (*SetValueResponse, error) {
	out := new(SetValueResponse)
	err := c.cc.Invoke(ctx, "/apidefinitions.keyval.KeyValueService/SetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyValueServiceClient) Transact(ctx context.Context, opts ...grpc.CallOption) (KeyValueService_TransactClient, error) {
	stream, err := c.cc.NewStream(ctx, &KeyValueService_ServiceDesc.Streams[0], "/apidefinitions.keyval.KeyValueService/Transact", opts...)
	if err != nil {
		return nil, err
	}
	x := &keyValueServiceTransactClient{stream}
	return x, nil
}

type KeyValueService_TransactClient interface {
	Send(*TransactRequest) error
	Recv() (*TransactResponse, error)
	grpc.ClientStream
}

type keyValueServiceTransactClient struct {
	grpc.ClientStream
}

func (x *keyValueServiceTransactClient) Send(m *TransactRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *keyValueServiceTransactClient) Recv() (*TransactResponse, error) {
	m := new(TransactResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyValueServiceServer is the server API for KeyValueService service.
// All implementations must embed UnimplementedKeyValueServiceServer
// for forward compatibility
type KeyValueServiceServer interface {
	HasValue(context.Context, *HasValueRequest) (*HasValueResponse, error)
	GetValue(context.Context, *GetValueRequest) (*Value, error)
	SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error)
	Transact(KeyValueService_TransactServer) error
	mustEmbedUnimplementedKeyValueServiceServer()
}

// UnimplementedKeyValueServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyValueServiceServer struct {
}

func (UnimplementedKeyValueServiceServer) HasValue(context.Context, *HasValueRequest) (*HasValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HasValue not implemented")
}
func (UnimplementedKeyValueServiceServer) GetValue(context.Context, *GetValueRequest) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedKeyValueServiceServer) SetValue(context.Context, *SetValueRequest) (*SetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedKeyValueServiceServer) Transact(KeyValueService_TransactServer) error {
	return status.Errorf(codes.Unimplemented, "method Transact not implemented")
}
func (UnimplementedKeyValueServiceServer) mustEmbedUnimplementedKeyValueServiceServer() {}

// UnsafeKeyValueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyValueServiceServer will
// result in compilation errors.
type UnsafeKeyValueServiceServer interface {
	mustEmbedUnimplementedKeyValueServiceServer()
}

func RegisterKeyValueServiceServer(s grpc.ServiceRegistrar, srv KeyValueServiceServer) {
	s.RegisterService(&KeyValueService_ServiceDesc, srv)
}

func _KeyValueService_HasValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).HasValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidefinitions.keyval.KeyValueService/HasValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).HasValue(ctx, req.(*HasValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidefinitions.keyval.KeyValueService/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).GetValue(ctx, req.(*GetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyValueServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apidefinitions.keyval.KeyValueService/SetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyValueServiceServer).SetValue(ctx, req.(*SetValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyValueService_Transact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyValueServiceServer).Transact(&keyValueServiceTransactServer{stream})
}

type KeyValueService_TransactServer interface {
	Send(*TransactResponse) error
	Recv() (*TransactRequest, error)
	grpc.ServerStream
}

type keyValueServiceTransactServer struct {
	grpc.ServerStream
}

func (x *keyValueServiceTransactServer) Send(m *TransactResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *keyValueServiceTransactServer) Recv() (*TransactRequest, error) {
	m := new(TransactRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// KeyValueService_ServiceDesc is the grpc.ServiceDesc for KeyValueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyValueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apidefinitions.keyval.KeyValueService",
	HandlerType: (*KeyValueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HasValue",
			Handler:    _KeyValueService_HasValue_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _KeyValueService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _KeyValueService_SetValue_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Transact",
			Handler:       _KeyValueService_Transact_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/keyval.proto",
}
