// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0--rc2
// source: proto/keyval.proto

package keyvalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are assignable to Action:
	//	*TransactRequest_GetValueRequest
	//	*TransactRequest_HasValueRequest
	//	*TransactRequest_SetValueRequest
	//	*TransactRequest_CommitRequest_
	//	*TransactRequest_AbortRequest_
	Action isTransactRequest_Action `protobuf_oneof:"action"`
}

func (x *TransactRequest) Reset() {
	*x = TransactRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactRequest) ProtoMessage() {}

func (x *TransactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactRequest.ProtoReflect.Descriptor instead.
func (*TransactRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{0}
}

func (x *TransactRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (m *TransactRequest) GetAction() isTransactRequest_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (x *TransactRequest) GetGetValueRequest() *GetValueRequest {
	if x, ok := x.GetAction().(*TransactRequest_GetValueRequest); ok {
		return x.GetValueRequest
	}
	return nil
}

func (x *TransactRequest) GetHasValueRequest() *HasValueRequest {
	if x, ok := x.GetAction().(*TransactRequest_HasValueRequest); ok {
		return x.HasValueRequest
	}
	return nil
}

func (x *TransactRequest) GetSetValueRequest() *SetValueRequest {
	if x, ok := x.GetAction().(*TransactRequest_SetValueRequest); ok {
		return x.SetValueRequest
	}
	return nil
}

func (x *TransactRequest) GetCommitRequest() *TransactRequest_CommitRequest {
	if x, ok := x.GetAction().(*TransactRequest_CommitRequest_); ok {
		return x.CommitRequest
	}
	return nil
}

func (x *TransactRequest) GetAbortRequest() *TransactRequest_AbortRequest {
	if x, ok := x.GetAction().(*TransactRequest_AbortRequest_); ok {
		return x.AbortRequest
	}
	return nil
}

type isTransactRequest_Action interface {
	isTransactRequest_Action()
}

type TransactRequest_GetValueRequest struct {
	GetValueRequest *GetValueRequest `protobuf:"bytes,2,opt,name=get_value_request,json=getValueRequest,proto3,oneof"`
}

type TransactRequest_HasValueRequest struct {
	HasValueRequest *HasValueRequest `protobuf:"bytes,3,opt,name=has_value_request,json=hasValueRequest,proto3,oneof"`
}

type TransactRequest_SetValueRequest struct {
	SetValueRequest *SetValueRequest `protobuf:"bytes,4,opt,name=set_value_request,json=setValueRequest,proto3,oneof"`
}

type TransactRequest_CommitRequest_ struct {
	CommitRequest *TransactRequest_CommitRequest `protobuf:"bytes,5,opt,name=commit_request,json=commitRequest,proto3,oneof"`
}

type TransactRequest_AbortRequest_ struct {
	AbortRequest *TransactRequest_AbortRequest `protobuf:"bytes,6,opt,name=abort_request,json=abortRequest,proto3,oneof"`
}

func (*TransactRequest_GetValueRequest) isTransactRequest_Action() {}

func (*TransactRequest_HasValueRequest) isTransactRequest_Action() {}

func (*TransactRequest_SetValueRequest) isTransactRequest_Action() {}

func (*TransactRequest_CommitRequest_) isTransactRequest_Action() {}

func (*TransactRequest_AbortRequest_) isTransactRequest_Action() {}

type TransactResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are assignable to Response:
	//	*TransactResponse_GetValueResponse
	//	*TransactResponse_HasValueResponse
	//	*TransactResponse_SetValueResponse
	//	*TransactResponse_CommitResponse_
	//	*TransactResponse_AbortResponse_
	Response isTransactResponse_Response `protobuf_oneof:"response"`
}

func (x *TransactResponse) Reset() {
	*x = TransactResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse) ProtoMessage() {}

func (x *TransactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse.ProtoReflect.Descriptor instead.
func (*TransactResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{1}
}

func (x *TransactResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (m *TransactResponse) GetResponse() isTransactResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *TransactResponse) GetGetValueResponse() *Value {
	if x, ok := x.GetResponse().(*TransactResponse_GetValueResponse); ok {
		return x.GetValueResponse
	}
	return nil
}

func (x *TransactResponse) GetHasValueResponse() *HasValueResponse {
	if x, ok := x.GetResponse().(*TransactResponse_HasValueResponse); ok {
		return x.HasValueResponse
	}
	return nil
}

func (x *TransactResponse) GetSetValueResponse() *SetValueResponse {
	if x, ok := x.GetResponse().(*TransactResponse_SetValueResponse); ok {
		return x.SetValueResponse
	}
	return nil
}

func (x *TransactResponse) GetCommitResponse() *TransactResponse_CommitResponse {
	if x, ok := x.GetResponse().(*TransactResponse_CommitResponse_); ok {
		return x.CommitResponse
	}
	return nil
}

func (x *TransactResponse) GetAbortResponse() *TransactResponse_AbortResponse {
	if x, ok := x.GetResponse().(*TransactResponse_AbortResponse_); ok {
		return x.AbortResponse
	}
	return nil
}

type isTransactResponse_Response interface {
	isTransactResponse_Response()
}

type TransactResponse_GetValueResponse struct {
	GetValueResponse *Value `protobuf:"bytes,2,opt,name=get_value_response,json=getValueResponse,proto3,oneof"`
}

type TransactResponse_HasValueResponse struct {
	HasValueResponse *HasValueResponse `protobuf:"bytes,3,opt,name=has_value_response,json=hasValueResponse,proto3,oneof"`
}

type TransactResponse_SetValueResponse struct {
	SetValueResponse *SetValueResponse `protobuf:"bytes,4,opt,name=set_value_response,json=setValueResponse,proto3,oneof"`
}

type TransactResponse_CommitResponse_ struct {
	CommitResponse *TransactResponse_CommitResponse `protobuf:"bytes,5,opt,name=commit_response,json=commitResponse,proto3,oneof"`
}

type TransactResponse_AbortResponse_ struct {
	AbortResponse *TransactResponse_AbortResponse `protobuf:"bytes,6,opt,name=abort_response,json=abortResponse,proto3,oneof"`
}

func (*TransactResponse_GetValueResponse) isTransactResponse_Response() {}

func (*TransactResponse_HasValueResponse) isTransactResponse_Response() {}

func (*TransactResponse_SetValueResponse) isTransactResponse_Response() {}

func (*TransactResponse_CommitResponse_) isTransactResponse_Response() {}

func (*TransactResponse_AbortResponse_) isTransactResponse_Response() {}

type SetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          *Key   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value        *Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	DatabaseName string `protobuf:"bytes,3,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	Overwrite    *bool  `protobuf:"varint,4,opt,name=overwrite,proto3,oneof" json:"overwrite,omitempty"`
}

func (x *SetValueRequest) Reset() {
	*x = SetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueRequest) ProtoMessage() {}

func (x *SetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueRequest.ProtoReflect.Descriptor instead.
func (*SetValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{2}
}

func (x *SetValueRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetValueRequest) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetValueRequest) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *SetValueRequest) GetOverwrite() bool {
	if x != nil && x.Overwrite != nil {
		return *x.Overwrite
	}
	return false
}

type SetValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetValueResponse) Reset() {
	*x = SetValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetValueResponse) ProtoMessage() {}

func (x *SetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetValueResponse.ProtoReflect.Descriptor instead.
func (*SetValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{3}
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyBytes []byte `protobuf:"bytes,1,opt,name=key_bytes,json=keyBytes,proto3" json:"key_bytes,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{4}
}

func (x *Key) GetKeyBytes() []byte {
	if x != nil {
		return x.KeyBytes
	}
	return nil
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueBytes []byte `protobuf:"bytes,1,opt,name=value_bytes,json=valueBytes,proto3" json:"value_bytes,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetValueBytes() []byte {
	if x != nil {
		return x.ValueBytes
	}
	return nil
}

type GetValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetValueRequest) Reset() {
	*x = GetValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueRequest) ProtoMessage() {}

func (x *GetValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueRequest.ProtoReflect.Descriptor instead.
func (*GetValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{6}
}

func (x *GetValueRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type HasValueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *HasValueRequest) Reset() {
	*x = HasValueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasValueRequest) ProtoMessage() {}

func (x *HasValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasValueRequest.ProtoReflect.Descriptor instead.
func (*HasValueRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{7}
}

func (x *HasValueRequest) GetKey() *Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type HasValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EntryExists bool `protobuf:"varint,1,opt,name=entry_exists,json=entryExists,proto3" json:"entry_exists,omitempty"`
}

func (x *HasValueResponse) Reset() {
	*x = HasValueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HasValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HasValueResponse) ProtoMessage() {}

func (x *HasValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HasValueResponse.ProtoReflect.Descriptor instead.
func (*HasValueResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{8}
}

func (x *HasValueResponse) GetEntryExists() bool {
	if x != nil {
		return x.EntryExists
	}
	return false
}

type TransactRequest_CommitRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransactRequest_CommitRequest) Reset() {
	*x = TransactRequest_CommitRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactRequest_CommitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactRequest_CommitRequest) ProtoMessage() {}

func (x *TransactRequest_CommitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactRequest_CommitRequest.ProtoReflect.Descriptor instead.
func (*TransactRequest_CommitRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{0, 0}
}

type TransactRequest_AbortRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransactRequest_AbortRequest) Reset() {
	*x = TransactRequest_AbortRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactRequest_AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactRequest_AbortRequest) ProtoMessage() {}

func (x *TransactRequest_AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactRequest_AbortRequest.ProtoReflect.Descriptor instead.
func (*TransactRequest_AbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{0, 1}
}

type TransactResponse_CommitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransactResponse_CommitResponse) Reset() {
	*x = TransactResponse_CommitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse_CommitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse_CommitResponse) ProtoMessage() {}

func (x *TransactResponse_CommitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse_CommitResponse.ProtoReflect.Descriptor instead.
func (*TransactResponse_CommitResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{1, 0}
}

type TransactResponse_AbortResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TransactResponse_AbortResponse) Reset() {
	*x = TransactResponse_AbortResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_keyval_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactResponse_AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactResponse_AbortResponse) ProtoMessage() {}

func (x *TransactResponse_AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keyval_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactResponse_AbortResponse.ProtoReflect.Descriptor instead.
func (*TransactResponse_AbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_keyval_proto_rawDescGZIP(), []int{1, 1}
}

var File_proto_keyval_proto protoreflect.FileDescriptor

var file_proto_keyval_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x22, 0x98, 0x04, 0x0a, 0x0f,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x54,
	0x0a, 0x11, 0x67, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61,
	0x6c, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0f, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x11, 0x68, 0x61, 0x73, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x68, 0x61, 0x73, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x11, 0x73, 0x65,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x0f, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x5d, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x34, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65,
	0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c,
	0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x5a, 0x0a, 0x0d, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0c, 0x61,
	0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x0a, 0x0d, 0x43,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x0a, 0x0c,
	0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x08, 0x0a, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa3, 0x04, 0x0a, 0x10, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x4c, 0x0a, 0x12, 0x67, 0x65,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x10, 0x67, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x57, 0x0a, 0x12, 0x68, 0x61, 0x73, 0x5f,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x73,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x10, 0x68, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x57, 0x0a, 0x12, 0x73, 0x65, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b,
	0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x73, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x61, 0x0a, 0x0f, 0x63, 0x6f,
	0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x36, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6d,
	0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x63,
	0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a,
	0x0e, 0x61, 0x62, 0x6f, 0x72, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41,
	0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0d,
	0x61, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x10, 0x0a,
	0x0e, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a,
	0x0f, 0x0a, 0x0d, 0x41, 0x62, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc9, 0x01, 0x0a,
	0x0f, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b,
	0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x32,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e,
	0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b,
	0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x62,
	0x61, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x09, 0x6f, 0x76, 0x65, 0x72, 0x77,
	0x72, 0x69, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x76,
	0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f,
	0x76, 0x65, 0x72, 0x77, 0x72, 0x69, 0x74, 0x65, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x22, 0x0a, 0x03,
	0x4b, 0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x22, 0x28, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76,
	0x61, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x3f, 0x0a, 0x0f, 0x48,
	0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70,
	0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79,
	0x76, 0x61, 0x6c, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x35, 0x0a, 0x10,
	0x48, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x21, 0x0a, 0x0c, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x65, 0x78, 0x69, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x45, 0x78, 0x69,
	0x73, 0x74, 0x73, 0x32, 0x86, 0x03, 0x0a, 0x0f, 0x4b, 0x65, 0x79, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x73, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79,
	0x76, 0x61, 0x6c, 0x2e, 0x48, 0x61, 0x73, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x70, 0x69,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76,
	0x61, 0x6c, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x5d, 0x0a, 0x08, 0x53, 0x65,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53,
	0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27,
	0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x61, 0x0a, 0x08, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x12, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e,
	0x61, 0x70, 0x69, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6b,
	0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2d, 0x64,
	0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6b, 0x65, 0x79, 0x76, 0x61,
	0x6c, 0x2f, 0x67, 0x6f, 0x2f, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_keyval_proto_rawDescOnce sync.Once
	file_proto_keyval_proto_rawDescData = file_proto_keyval_proto_rawDesc
)

func file_proto_keyval_proto_rawDescGZIP() []byte {
	file_proto_keyval_proto_rawDescOnce.Do(func() {
		file_proto_keyval_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_keyval_proto_rawDescData)
	})
	return file_proto_keyval_proto_rawDescData
}

var file_proto_keyval_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_keyval_proto_goTypes = []interface{}{
	(*TransactRequest)(nil),                 // 0: apidefinitions.keyval.TransactRequest
	(*TransactResponse)(nil),                // 1: apidefinitions.keyval.TransactResponse
	(*SetValueRequest)(nil),                 // 2: apidefinitions.keyval.SetValueRequest
	(*SetValueResponse)(nil),                // 3: apidefinitions.keyval.SetValueResponse
	(*Key)(nil),                             // 4: apidefinitions.keyval.Key
	(*Value)(nil),                           // 5: apidefinitions.keyval.Value
	(*GetValueRequest)(nil),                 // 6: apidefinitions.keyval.GetValueRequest
	(*HasValueRequest)(nil),                 // 7: apidefinitions.keyval.HasValueRequest
	(*HasValueResponse)(nil),                // 8: apidefinitions.keyval.HasValueResponse
	(*TransactRequest_CommitRequest)(nil),   // 9: apidefinitions.keyval.TransactRequest.CommitRequest
	(*TransactRequest_AbortRequest)(nil),    // 10: apidefinitions.keyval.TransactRequest.AbortRequest
	(*TransactResponse_CommitResponse)(nil), // 11: apidefinitions.keyval.TransactResponse.CommitResponse
	(*TransactResponse_AbortResponse)(nil),  // 12: apidefinitions.keyval.TransactResponse.AbortResponse
}
var file_proto_keyval_proto_depIdxs = []int32{
	6,  // 0: apidefinitions.keyval.TransactRequest.get_value_request:type_name -> apidefinitions.keyval.GetValueRequest
	7,  // 1: apidefinitions.keyval.TransactRequest.has_value_request:type_name -> apidefinitions.keyval.HasValueRequest
	2,  // 2: apidefinitions.keyval.TransactRequest.set_value_request:type_name -> apidefinitions.keyval.SetValueRequest
	9,  // 3: apidefinitions.keyval.TransactRequest.commit_request:type_name -> apidefinitions.keyval.TransactRequest.CommitRequest
	10, // 4: apidefinitions.keyval.TransactRequest.abort_request:type_name -> apidefinitions.keyval.TransactRequest.AbortRequest
	5,  // 5: apidefinitions.keyval.TransactResponse.get_value_response:type_name -> apidefinitions.keyval.Value
	8,  // 6: apidefinitions.keyval.TransactResponse.has_value_response:type_name -> apidefinitions.keyval.HasValueResponse
	3,  // 7: apidefinitions.keyval.TransactResponse.set_value_response:type_name -> apidefinitions.keyval.SetValueResponse
	11, // 8: apidefinitions.keyval.TransactResponse.commit_response:type_name -> apidefinitions.keyval.TransactResponse.CommitResponse
	12, // 9: apidefinitions.keyval.TransactResponse.abort_response:type_name -> apidefinitions.keyval.TransactResponse.AbortResponse
	4,  // 10: apidefinitions.keyval.SetValueRequest.key:type_name -> apidefinitions.keyval.Key
	5,  // 11: apidefinitions.keyval.SetValueRequest.value:type_name -> apidefinitions.keyval.Value
	4,  // 12: apidefinitions.keyval.GetValueRequest.key:type_name -> apidefinitions.keyval.Key
	4,  // 13: apidefinitions.keyval.HasValueRequest.key:type_name -> apidefinitions.keyval.Key
	7,  // 14: apidefinitions.keyval.KeyValueService.HasValue:input_type -> apidefinitions.keyval.HasValueRequest
	6,  // 15: apidefinitions.keyval.KeyValueService.GetValue:input_type -> apidefinitions.keyval.GetValueRequest
	2,  // 16: apidefinitions.keyval.KeyValueService.SetValue:input_type -> apidefinitions.keyval.SetValueRequest
	0,  // 17: apidefinitions.keyval.KeyValueService.Transact:input_type -> apidefinitions.keyval.TransactRequest
	8,  // 18: apidefinitions.keyval.KeyValueService.HasValue:output_type -> apidefinitions.keyval.HasValueResponse
	5,  // 19: apidefinitions.keyval.KeyValueService.GetValue:output_type -> apidefinitions.keyval.Value
	3,  // 20: apidefinitions.keyval.KeyValueService.SetValue:output_type -> apidefinitions.keyval.SetValueResponse
	1,  // 21: apidefinitions.keyval.KeyValueService.Transact:output_type -> apidefinitions.keyval.TransactResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_keyval_proto_init() }
func file_proto_keyval_proto_init() {
	if File_proto_keyval_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_keyval_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasValueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HasValueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactRequest_CommitRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactRequest_AbortRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactResponse_CommitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_keyval_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactResponse_AbortResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_keyval_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*TransactRequest_GetValueRequest)(nil),
		(*TransactRequest_HasValueRequest)(nil),
		(*TransactRequest_SetValueRequest)(nil),
		(*TransactRequest_CommitRequest_)(nil),
		(*TransactRequest_AbortRequest_)(nil),
	}
	file_proto_keyval_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*TransactResponse_GetValueResponse)(nil),
		(*TransactResponse_HasValueResponse)(nil),
		(*TransactResponse_SetValueResponse)(nil),
		(*TransactResponse_CommitResponse_)(nil),
		(*TransactResponse_AbortResponse_)(nil),
	}
	file_proto_keyval_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_keyval_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_keyval_proto_goTypes,
		DependencyIndexes: file_proto_keyval_proto_depIdxs,
		MessageInfos:      file_proto_keyval_proto_msgTypes,
	}.Build()
	File_proto_keyval_proto = out.File
	file_proto_keyval_proto_rawDesc = nil
	file_proto_keyval_proto_goTypes = nil
	file_proto_keyval_proto_depIdxs = nil
}
